### ISSUE TITLE
Feedsort at the Beginning

### ISSUE THREAD

**Issue by OlderHolder** [Emilmoldovan24/Tue-Tweet#111]
Wenn man auf die Feed Seite kommt dann hat es keine Sortierung , es gibt die Tweets und retweets einfach aus wie sie in der Datenbank sind . Dies geschieht auch wenn ich in profile ein setting ändere und zurück zu feed gehe bsp.  Evt. sollte man eine standard sortierung einstellen (newest)

**Comment by ayaafaghani** [comment]
Hab ich tatsächlich probiert aber leider nicht hinbekommen🥲

**Comment by OlderHolder** [comment]
Ah ok dann schieben wir das mal nach hinten , ist glaub auch nicht wild wenn es so bleibt

**Comment by OlderHolder** [comment]
Anfängliche Sortierung ist nicht Notwendig
