### ISSUE TITLE
Follows

### ISSUE THREAD

**Issue by OlderHolder** [Emilmoldovan24/Tue-Tweet#143]
Wenn man jemanden Folgt kommt bei mir diese Fehlermeldung in dem "account" des gefolgten 
![image](https://github.com/Emilmoldovan24/Tue-Tweet/assets/92357718/8c9aff2a-cc86-48b0-af0f-bc3c71913454)

**Comment by LukeVallon** [comment]
habe ich gefixt, gerne nochmal checken
