### ISSUE TITLE
Update Settings

### ISSUE THREAD

**Issue by JuliaLujlia** [Emilmoldovan24/Tue-Tweet#70]
# Problem
Wir haben die Funktion, dass wir sehen können, wann ein User sich seinen Account erstellt hat.
Ändern wir nun Sachen bei den Settings, so wird der created_at Stempel neu aufgesetzt. 
Das bedeutet "User Joined at ..." wird falsch angegeben.
 
![image](https://github.com/Emilmoldovan24/Tue-Tweet/assets/116385114/415d8ce3-c869-4a71-891b-1c1a5a9f9c7c)
wird zu:
![image](https://github.com/Emilmoldovan24/Tue-Tweet/assets/116385114/fe43cb2f-3b9d-41d7-90ca-bb04e4e1b8bb)

**Comment by OlderHolder** [comment]
fixxed
