### ISSUE TITLE
Re-Tweet

### ISSUE THREAD

**Issue by JuliaLujlia** [Emilmoldovan24/Tue-Tweet#83]
## Aufgabe

- Müssen lösen wie wir Re-Tweets und Tweets richtig anzeigen können.
- Außerdem müssen wir schauen wie wir die ID´s unterscheiden können.

**Comment by OlderHolder** [comment]
Hierzu wurde bereits in likes (darauf bezieht sich doch deine ID Unterscheidung oder? ) eine extra spalte mit retweet_id eingefügt . Damit sollte es nun möglich sein die tweet und retweet likes zu unterscheiden .

**Comment by LukeVallon** [comment]
Ja markus hat das schon gelöst. Julia und ich müssen nur noch die Funktion implementieren

**Comment by LukeVallon** [comment]
Bilder können noch nicht retweetet werden bzw werden im retweet nicht mehr angezeigt
