### ISSUE TITLE
Hide Tweet from public

### ISSUE THREAD

**Issue by JuliaLujlia** [Emilmoldovan24/Tue-Tweet#86]
## Aufgabe
Eigenen Tweet auf privat stellen
## Lösungsvorschlag
Analog zu HideTweet von den Admins

**Comment by OlderHolder** [comment]
Hierzu könnte ich eine Neue Spalte einfügen zb. own_visibility. Damit könnte man das relativ einfach umsetzen.

**Comment by JuliaLujlia** [comment]
Ja, es sollte ja so funktionieren, wie bei den Admins. Designmäßig müssten wir dann noch schauen!

**Comment by LukeVallon** [comment]
Ich glaube das feature funktioniert jetzt vollständig
