### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by JuliaLujlia** [Emilmoldovan24/Tue-Tweet#88]
## Aufgabe
Benachrichtigung bei ReTweets oder Kommentaren.

**Comment by OlderHolder** [comment]
Hier gibt es ja jetzt die neuen Spalten "notification_flag" die standartmäßig true sind.

Idee: man implementiert einen "Kasten" in der UI, der eine Schleife beinhaltet die alle , retweets, likes und comments mit  notification_flag == true   anzeigt . Wenn man nun diesen Kasten Öffnet soll dieser auch die Notificationflag ändern. 

Es gibt allerdings auch eine notification Funktion von Laravel (zumindest anhand der Docu)
