### ISSUE TITLE
Compute trending

### ISSUE THREAD

**Issue by JuliaLujlia** [Emilmoldovan24/Tue-Tweet#89]
## Aufgabe
Algorithmus entwerfen wie die Tweets/ReTweets im Feed angezeigt werden.
## Lösungsvorschlag
Wir schreiben einen Algorithmus, der die Likes aller Tweets und ReTweets zählt (kann man mit der LikeFunktion verbinden).

Trotzdem wäre es nicht so gut, wenn ein Tweet mit vielen Likes immer nur oben ist, dann sind alle neuen/aktuellen Tweets/ReTweets unten (irgendwann nicht mehr zu sehen), daher sollte der Algo noch die Aktualität beachten (currentTimeStample, den wir noch fixen müssen, sh. #70).

**Comment by OlderHolder** [comment]
Glaube Steven hat gemeint es reicht ihm wenn wir das anhand der Likes machen ohne einen Aufwendigeren Algo zu entwickeln.

**Comment by OlderHolder** [comment]
Fertig
