### ISSUE TITLE
Download own data into text file and its pictures

### ISSUE THREAD

**Issue by JuliaLujlia** [Emilmoldovan24/Tue-Tweet#90]
## Aufgabe
Eigene Daten in ein TextFile speichern.
## Lösungsvorschlag
- s.H. Arbeit von Markus
- optimiere es

**Comment by OlderHolder** [comment]
Muss noch in den Browser standard ordner gedownloadet werden

**Comment by OlderHolder** [comment]
sollte jetzt passen
