### ISSUE TITLE
Deleted Users

### ISSUE THREAD

**Issue by OlderHolder** [Emilmoldovan24/Tue-Tweet#95]
Wenn man einen user löscht (Soft-delete) oder der sich selber Löscht (was noch als Feature fehlt) dann kann dieser sich dennoch anmelden und tweets absetzen. 
-Ich denke es wäre hier Hilfreich wenn man das abfängt und mit einer Meldung versieht.

**Comment by lukas3540** [comment]
Bei admin login ist das implementiert. kann man rüber kopieren.

**Comment by OlderHolder** [comment]
erledigt
